version: '3'
services:
  db:
    container_name: db
    image: mysql
    env_file:
      - .env.mysql
    volumes:
      - ./mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    #networks:
    #  - db
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -h localhost" #this is mysql command to monitor if the localhost database is alive
      interval: 1s
      timeout: 1s
      retries: 60

  backend:
    container_name: backend
    build: .
    ports: 
      - "90:90"
    depends_on: 
      - db

