version: '3'
services:
  mydb:
    container_name: mydb
    image: mysql
    env_file:
      - .env.mysql
    volumes:
      - ./mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -h localhost" #this is mysql command to monitor if the localhost database is alive
      interval: 1s
      timeout: 1s
      retries: 60
      

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: back-dockerfile
    ports: 
      - "90:90"
    depends_on: 
      - mydb


  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: front-dockerfile
    ports: 
      - "8501:8501"
